{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "33e0ced7",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-12-01 11:39:58.041 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager\n",
      "2025-12-01 11:39:58.048 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager\n",
      "2025-12-01 11:39:58.053 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-01 11:40:02.794 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run c:\\Users\\mites\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-12-01 11:40:02.818 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-01 11:40:02.837 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-01 11:40:03.021 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-01 11:40:03.025 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-01 11:40:03.031 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-01 11:40:03.041 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-01 11:40:03.075 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-01 11:40:03.106 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-01 11:40:03.124 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-01 11:40:03.144 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-01 11:40:03.158 Session state does not function when running a script without `streamlit run`\n",
      "2025-12-01 11:40:03.160 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-01 11:40:03.205 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-01 11:40:03.209 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-01 11:40:03.211 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-01 11:40:03.218 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-01 11:40:03.256 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-01 11:40:03.278 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-01 11:40:03.304 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-01 11:40:03.311 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-01 11:40:03.324 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-01 11:40:03.391 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-01 11:40:03.394 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-01 11:40:03.434 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-01 11:40:03.491 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-01 11:40:03.500 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-01 11:40:03.502 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-01 11:40:03.508 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-01 11:40:03.511 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-01 11:40:03.523 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-01 11:40:03.594 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "DeltaGenerator(_root_container=1, _parent=DeltaGenerator())"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import plotly.express as px\n",
    "\n",
    "# Load data\n",
    "@st.cache_data\n",
    "def load_data():\n",
    "    return pd.read_csv('inventory_optimized.csv')\n",
    "\n",
    "df = load_data()\n",
    "\n",
    "# Page config\n",
    "st.set_page_config(page_title=\"Grocery AI Assistant\", layout=\"wide\")\n",
    "st.title(\"🛒 Grocery Inventory AI Assistant\")\n",
    "st.markdown(\"**Ask about stock, risks, urgent items, or reorders**\")\n",
    "\n",
    "# Chat history\n",
    "if \"messages\" not in st.session_state:\n",
    "    st.session_state.messages = []\n",
    "\n",
    "# Show chat history\n",
    "for message in st.session_state.messages:\n",
    "    with st.chat_message(message[\"role\"]):\n",
    "        st.markdown(message[\"content\"])\n",
    "\n",
    "# Chat input\n",
    "if prompt := st.chat_input(\"Ask about inventory...\"):\n",
    "    st.session_state.messages.append({\"role\": \"user\", \"content\": prompt})\n",
    "    with st.chat_message(\"user\"):\n",
    "        st.markdown(prompt)\n",
    "\n",
    "    # Get AI response\n",
    "    with st.chat_message(\"assistant\"):\n",
    "        response = get_ai_response(prompt.lower(), df)\n",
    "        st.markdown(response)\n",
    "        st.session_state.messages.append({\"role\": \"assistant\", \"content\": response})\n",
    "\n",
    "def get_ai_response(query, df):\n",
    "    \"\"\"Smart AI responses for managers\"\"\"\n",
    "    \n",
    "    # Urgent items\n",
    "    if any(word in query for word in ['urgent', 'risk', 'spoil', 'waste']):\n",
    "        urgent = df[df['Action_Priority'] == '🚨 URGENT'].head(5)\n",
    "        if len(urgent) > 0:\n",
    "            return f\"🚨 **{len(urgent)} URGENT ITEMS:**\\n\\n\" + urgent[['Product_Name', 'Waste_Risk_Score', 'Action_Priority']].round(2).to_string(index=False)\n",
    "        return \"✅ No urgent items right now!\"\n",
    "    \n",
    "    # Reorder needs\n",
    "    elif any(word in query for word in ['reorder', 'order', 'low', 'stock']):\n",
    "        reorder = df[df['Needs_Reorder'] == 1].head(5)\n",
    "        if len(reorder) > 0:\n",
    "            return f\"⚠️ **{len(reorder)} ITEMS NEED REORDER:**\\n\\n\" + reorder[['Product_Name', 'EOQ', 'Stock_Quantity']].round(0).to_string(index=False)\n",
    "        return \"✅ All stock levels good!\"\n",
    "    \n",
    "    # Perishables\n",
    "    elif any(word in query for word in ['perish', 'fruit', 'dairy']):\n",
    "        risky = df[df['Perishable'] == 1].sort_values('Waste_Risk_Score', ascending=False).head(5)\n",
    "        return f\"🍎 **TOP 5 RISKY PERISHABLES:**\\n\\n\" + risky[['Product_Name', 'Waste_Risk_Score']].round(2).to_string(index=False)\n",
    "    \n",
    "    # Summary\n",
    "    else:\n",
    "        urgent_count = len(df[df['Action_Priority'] == '🚨 URGENT'])\n",
    "        reorder_count = len(df[df['Needs_Reorder'] == 1])\n",
    "        return f\"**QUICK SUMMARY:**\\n🚨 {urgent_count} Urgent | ⚠️ {reorder_count} Reorders Needed | ✅ {len(df)-urgent_count-reorder_count} OK\"\n",
    "\n",
    "# Sidebar stats\n",
    "st.sidebar.title(\"📊 Quick Stats\")\n",
    "col1, col2, col3 = st.sidebar.columns(3)\n",
    "col1.metric(\"🚨 Urgent\", len(df[df['Action_Priority'] == '🚨 URGENT']))\n",
    "col2.metric(\"⚠️ Reorder\", len(df[df['Needs_Reorder'] == 1]))\n",
    "col3.metric(\"🍎 Perishables\", len(df[df['Perishable'] == 1]))\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
